name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Sync latest Unblocked Music source code
        run: |
          git clone --depth=1 https://github.com/benefit6/server.git
          cd server
          zip -r ../UnblockNeteaseMusic.zip .
          cd ..
          rm ./app/src/main/assets/UnblockNeteaseMusic.zip
          rm -rf server
          mv ./UnblockNeteaseMusic.zip ./app/src/main/assets/UnblockNeteaseMusic.zip

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew app:assembleRelease

      - name: List build outputs for debugging
        run: ls -R ${GITHUB_WORKSPACE}/app/build/outputs/apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
          asset_name: my_app.apk
          asset_content_type: application/vnd.android.package-archive
